export default [
    {
        id: 1,
        name: '구본혁',
        admission: 3,
        graduated: 4,
        prayerTopic: '중국복음화',
        liveIn: '중국',
        imgSrc: '',
    },
    {
        id: 2,
        name: '이승유',
        admission: 4,
        graduated: 4,
        prayerTopic: '',
        liveIn: '호주',
        imgSrc: '',
    },
    {
        id: 3,
        name: '최예원',
        admission: 5,
        graduated: 6,
        prayerTopic: '',
        liveIn: '',
        imgSrc: '',
    },
    {
        id: 4,
        name: '성소영',
        admission: 3,
        graduated: 6,
        prayerTopic: '',
        liveIn: '프랑스',
        imgSrc: '',
    },
    {
        id: 5,
        name: '김혜민',
        admission: 5,
        graduated: 7,
        prayerTopic: '',
        liveIn: '프랑스',
        imgSrc: '',
    },
    {
        id: 6,
        name: '최한길',
        admission: 10,
        graduated: 9,
        prayerTopic: '',
        liveIn: '미국',
        imgSrc: '',
    },
    {
        id: 7,
        name: '여호수아',
        admission: 12,
        graduated: '',
        prayerTopic: '',
        liveIn: '말레이시아',
        imgSrc: '',
    },
    {
        id: 8,
        name: '원재희',
        admission: 12,
        graduated: 15,
        prayerTopic:
            '잠언22:29, 행9:15, 렘1:5 / 어디에 있든지 무엇을 하든지 하나님께 예배하는 예배자, 나를 통해 복음이 전달되는 전도자, 기도에 의해 살아가는 기도의 사람',
        liveIn: '라트비아',
        imgSrc: '',
    },
    {
        id: 9,
        name: '정다빈',
        admission: 4,
        graduated: '',
        prayerTopic: '',
        liveIn: '시카고',
        imgSrc: '',
    },
    {
        id: 10,
        name: '강승혁',
        admission: 13,
        graduated: 16,
        prayerTopic:
            '1,3,8,14 집중 속에서 24응답 누릴 수 있도록, 뉴질랜드 8개 대학을 살리는 복음 전도자가 되게',
        liveIn: '오클랜드',
        imgSrc: '',
    },
    {
        id: 11,
        name: '아끼야마 히까리',
        admission: 7,
        graduated: 6,
        prayerTopic:
            '현장목회, 20전도전략증인 엘리사 7000 도단성 운동, 일본 렘넌트운동, 일본 RLS, 일본 선교시대, 일본 목회자들의 동역자',
        liveIn: '일본',
        imgSrc: '',
    },
    {
        id: 12,
        name: '정민석',
        admission: 9,
        graduated: 9,
        prayerTopic: '내가 가는 현장에 예비 된 하나님의 응답 발견할 수 있도록',
        liveIn: '일본',
        imgSrc: '',
    },
    {
        id: 13,
        name: '고바야시 히로야끼',
        admission: 10,
        graduated: '',
        prayerTopic: '일본 RLS',
        liveIn: '일본',
        imgSrc: '',
    },
    {
        id: 14,
        name: '이성인',
        admission: 3,
        graduated: 6,
        prayerTopic:
            '일본 지역에 RLS,RUTC 센터 치유사역원이 세워 지도록, 과거의 잃어버린 기억을 복음 안에서 발견하도록, 마음껏 복음을 들을 수있는 환경으로 인도받도록',
        liveIn: '일본',
        imgSrc: '',
    },
    {
        id: 15,
        name: '정시영',
        admission: 9,
        graduated: '',
        prayerTopic:
            '말씀이 드려지는 예배 회복, 세상의 육에서 하나님의 나라로 들어올 수 있는 하나님의 인도, 네피림 시대, 흑암 시대의 빛을 비추는 이 시대의 선교사, 전도자',
        liveIn: '홍콩',
        imgSrc: '',
    },
    {
        id: 16,
        name: '미우라 마사토',
        admission: 8,
        graduated: '',
        prayerTopic: '임마누엘 누리게 하소서',
        liveIn: '일본',
        imgSrc: '',
    },
    {
        id: 17,
        name: '김준기',
        admission: 5,
        graduated: 5,
        prayerTopic: '완전 복음 체질되게',
        liveIn: '미국',
        imgSrc: '',
    },
    {
        id: 18,
        name: '이효은',
        admission: 4,
        graduated: '',
        prayerTopic: '',
        liveIn: '일본',
        imgSrc: '',
    },
    {
        id: 19,
        name: '지성원',
        admission: 1,
        graduated: 3,
        prayerTopic: '',
        liveIn: '일본',
        imgSrc: '',
    },
    {
        id: 20,
        name: '김준영',
        admission: 1,
        graduated: 3,
        prayerTopic: '항상 기도하는 사람',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 21,
        name: '황유정',
        admission: 2,
        graduated: 3,
        prayerTopic: '그리스도의 증인되게',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 22,
        name: '왕혜리',
        admission: 4,
        graduated: 4,
        prayerTopic: '오직 예수 그리스도만 남기는 인생',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 23,
        name: '주기쁨',
        admission: 4,
        graduated: 4,
        prayerTopic: '',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 24,
        name: '권수진',
        admission: 1,
        graduated: 5,
        prayerTopic: '',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 25,
        name: '차지훈',
        admission: 1,
        graduated: 5,
        prayerTopic: '',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 26,
        name: '이도숙',
        admission: 4,
        graduated: 5,
        prayerTopic: '',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 27,
        name: '윤찬미',
        admission: 3,
        graduated: 5,
        prayerTopic: '',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 28,
        name: '이희성',
        admission: 3,
        graduated: 5,
        prayerTopic: '',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 29,
        name: '이유진',
        admission: 4,
        graduated: 5,
        prayerTopic:
            '평생의 청사진을 가슴에 품고 어떤 상황, 어떤 환경, 어떠한 현장에서든 반짝반짝 빛(이사야60장)나는 빛 발하는 언약의 여정을 살아가도록',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 30,
        name: '황에스더',
        admission: 6,
        graduated: 6,
        prayerTopic:
            '바알한테 무릎 꿇지 않는 미용 제자 7000만 일어나게, 반석 위의 하나님의 3기업, 전도자의 자랑, 작품, 증인, 지도자의 대열 속에, 실제 엘리트층을 상대할 중화권 속에 하나님이 예비해 두신 두기고 같은 제자 팀을 붙여주소서',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 31,
        name: '양주훈',
        admission: 6,
        graduated: 6,
        prayerTopic: '그리스도로 결론 난 제자',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 32,
        name: '이지은',
        admission: 5,
        graduated: 6,
        prayerTopic: '그리스도로 결론 난 제자',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 33,
        name: '양지혜',
        admission: 2,
        graduated: 6,
        prayerTopic:
            '날마다 새로운 그리스도의 옷을 입고 치유선교사로서의 영성 집중과 그릇 준비',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 34,
        name: '권병욱',
        admission: 7,
        graduated: 7,
        prayerTopic: '날마다 성령충만',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 35,
        name: '문인주',
        admission: 7,
        graduated: 7,
        prayerTopic: '하나님의 자녀의 권세를 날마다 누리게',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 36,
        name: '전은혜',
        admission: 7,
        graduated: 7,
        prayerTopic:
            '영유아들을 복음으로 각인 뿌리 체질 내리며 올바르게 발달 성장시키는 교사, 미션 홈 가정(‭‭사도행전‬ ‭16:14‬)을 이루어 렘넌트를 키우고 가정을 살리는 가정을 꾸리도록, 세계복음화의 증인으로 쓰임 받도록',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 37,
        name: '황선',
        admission: 7,
        graduated: 7,
        prayerTopic:
            '나와 내 가문을 통해 전 세계 곳곳에 100개 RUTC가 세워지도록, 세계복음화 때문에 늘 5력 충만하도록, 교회에 든든한 기둥, 목회자의 오른팔, 후대 살리는 주역이 되도록',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 38,
        name: '박슬기',
        admission: 1,
        graduated: 8,
        prayerTopic: '최고의 성령충만',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 39,
        name: '장성결',
        admission: 4,
        graduated: 8,
        prayerTopic: ' 성령내주, 성령인도, 성령충만, 절대주권',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 40,
        name: '한지혜',
        admission: 11,
        graduated: 9,
        prayerTopic:
            '내 삶의 이유와 목적, 미래 목표, 나를 이 현장에 보내신 하나님의 이유를 잊지 않게, 항상 말씀 흐름 속에 있도록, 흔들려도 결국에는 주님 품으로 돌아올 수 있도록, 훈련하는 시간표, 기도 성공',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 41,
        name: '성진하',
        admission: 11,
        graduated: 10,
        prayerTopic:
            '내 삶의 이유와 목적, 미래 목표, 나를 이 현장에 보내신 하나님의 이유를 잊지 않게, 항상 말씀 흐름 속에 있도록, 흔들려도 결국에는 주님 품으로 돌아올 수 있도록, 훈련하는 시간표, 기도 성공',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 42,
        name: '신반석',
        admission: 9,
        graduated: 11,
        prayerTopic: '참된 성공할 수 있게',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 42,
        name: '박민균',
        admission: 10,
        graduated: 12,
        prayerTopic: '하나님과 함께하는 삶',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 43,
        name: '정가람',
        admission: 7,
        graduated: 7,
        prayerTopic: '하나님께 영광 돌리는 삶',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 44,
        name: '허재성',
        admission: 13,
        graduated: 12,
        prayerTopic: '복음 누리는 게임을 만드는 힘과 기도를 얻도록',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 45,
        name: '김현중',
        admission: 13,
        graduated: 12,
        prayerTopic: '정체성, 천명 각인',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 46,
        name: '윤소현',
        admission: 12,
        graduated: 14,
        prayerTopic: '행27:24의 증인되게, 그리스도를 위해 사는 자',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 47,
        name: '강은택',
        admission: 5,
        graduated: '',
        prayerTopic:
            '히4:12 하나님 말씀을 통해 변화되는 축복을 받을 수 있게, 하나님과의 관계가 더욱 깊어지는 한 해가 되도록, 그리스도로 모든 것을 답 내리고 인생의 결론을 내릴 수 있게',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 48,
        name: '김희태',
        admission: 9,
        graduated: 11,
        prayerTopic: '깊은 기도 속에서 영적서밋으로 올라갈 수 있게',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 49,
        name: '이은혜',
        admission: 15,
        graduated: 17,
        prayerTopic: '딤후2:1-2, 237나라의 후대를 살리는 RUTC 운동의 증인',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 50,
        name: '강혜림',
        admission: 6,
        graduated: 9,
        prayerTopic: '성령충만',
        liveIn: '서울',
        imgSrc: '',
    },
    {
        id: 51,
        name: '심이삭',
        admission: 1,
        graduated: 3,
        prayerTopic: '20가지 전도 전략의 증인',
        liveIn: '경기(안성)',
        imgSrc: '',
    },
    {
        id: 52,
        name: '심안나',
        admission: 2,
        graduated: 3,
        prayerTopic: '',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 53,
        name: '김준수',
        admission: 2,
        graduated: 4,
        prayerTopic: '20가지 전략의 증인',
        liveIn: '경기(안산)',
        imgSrc: '',
    },
    {
        id: 54,
        name: '박재준',
        admission: 4,
        graduated: 4,
        prayerTopic:
            '골3:9-10 의 응답을 통해 국가와 민족살릴 사무엘의 응답받길',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 55,
        name: '강효윤',
        admission: 2,
        graduated: 4,
        prayerTopic:
            '골3:9-10 의 응답을 통해 국가와 민족살릴 사무엘의 응답받길',
        liveIn: '경기(의정부)',
        imgSrc: '',
    },
    {
        id: 56,
        name: '이선민',
        admission: 1,
        graduated: 4,
        prayerTopic: '',
        liveIn: '경기(안산)',
        imgSrc: '',
    },
    {
        id: 57,
        name: '전건희',
        admission: 6,
        graduated: 6,
        prayerTopic: '',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 58,
        name: '박진영',
        admission: 1,
        graduated: 6,
        prayerTopic: '매일 그리스도를 누리는 시간 가지기',
        liveIn: '경기(안산)',
        imgSrc: '',
    },
    {
        id: 59,
        name: '진은주',
        admission: 7,
        graduated: 7,
        prayerTopic: '매일 날마다 성령인도받을 수 있게',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 60,
        name: '박정인',
        admission: 6,
        graduated: 7,
        prayerTopic: '날마다 성령충만',
        liveIn: '경기(평택)',
        imgSrc: '',
    },
    {
        id: 61,
        name: '박명우',
        admission: 5,
        graduated: 7,
        prayerTopic: '명품 인생',
        liveIn: '경기(안산)',
        imgSrc: '',
    },
    {
        id: 62,
        name: '유한나',
        admission: 8,
        graduated: 7,
        prayerTopic: '항상 그리스도의 언약 속에서',
        liveIn: '경기(수원)',
        imgSrc: '',
    },
    {
        id: 63,
        name: '박기찬',
        admission: 6,
        graduated: 7,
        prayerTopic: '성경에서 말하는 7가지 핵의 증인',
        liveIn: '경기(광명)',
        imgSrc: '',
    },
    {
        id: 64,
        name: '박민지',
        admission: 5,
        graduated: 7,
        prayerTopic:
            '보육 실습하는 가운데, 여러 가지 어려움이 기회가 되게 하시고, 감당할 수 있는 힘주세요. 후대, RT 키울 최고의 준비 기간이 되게 해주세요, 영적 무기력 상태에 빠지지 않고, 적 지속으로 세상 살릴 영적 서밋 될 수 있도록 하나님이 나의 힘, 나의 능력, 나의 배경 되게 하옵소서',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 65,
        name: '오바울',
        admission: 6,
        graduated: 8,
        prayerTopic: '하나님을 더 깊이 아는 것, 모든 과정 성령인도 받는 것',
        liveIn: '경기(수원)',
        imgSrc: '',
    },
    {
        id: 66,
        name: '서륜동',
        admission: 6,
        graduated: 9,
        prayerTopic: '예배 회복',
        liveIn: '경기(수원)',
        imgSrc: '',
    },
    {
        id: 67,
        name: '정신영',
        admission: 8,
        graduated: 8,
        prayerTopic: '예배 회복',
        liveIn: '경기(안산)',
        imgSrc: '',
    },
    {
        id: 68,
        name: '장재석',
        admission: 5,
        graduated: 9,
        prayerTopic: '믿음이 회복되고 영적정체성이 회복되고 예배성공 하길',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 69,
        name: '이유광',
        admission: 7,
        graduated: 9,
        prayerTopic: '',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 70,
        name: '박수인',
        admission: 7,
        graduated: 9,
        prayerTopic: '',
        liveIn: '경기(평택)',
        imgSrc: '',
    },
    {
        id: 71,
        name: '양은혜',
        admission: 7,
        graduated: 9,
        prayerTopic:
            '그리스도가 필요한 게 아니라 그리스도여야만하는 사람, 모든 현장에서 모든 것을 전도, 선교의 눈으로 보는 사람',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 72,
        name: '김하영',
        admission: 8,
        graduated: 9,
        prayerTopic:
            '내 삶이 온전히 하나님과 함께하는 삶, 내 인생이 온전히 하나님 자녀로써 쓰임 받는 인생 되게 해 주세요',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 73,
        name: '김은진',
        admission: 9,
        graduated: 9,
        prayerTopic: '오직 성령충만, 오직 그리스도, 오직 하나님 나라와 그의 일',
        liveIn: '경기(파주)',
        imgSrc: '',
    },
    {
        id: 74,
        name: '남수환',
        admission: 10,
        graduated: 9,
        prayerTopic: '말씀 자립, 전도 자립, 기도 자립',
        liveIn: '경기(원주)',
        imgSrc: '',
    },
    {
        id: 75,
        name: '표창민',
        admission: 10,
        graduated: 10,
        prayerTopic: '어떤 상황, 문제가 와도 기도의 사람이 될 수 있도록',
        liveIn: '경기(원주)',
        imgSrc: '',
    },
    {
        id: 76,
        name: '신다해',
        admission: 11,
        graduated: 10,
        prayerTopic: '',
        liveIn: '경기(수원)',
        imgSrc: '',
    },
    {
        id: 77,
        name: '조대곤',
        admission: 10,
        graduated: 10,
        prayerTopic:
            '나의 힘이 아닌 하나님의 힘으로 영적인 힘 회복하고 하나님 계획 속에 나를 발견하고 그 인도 따라가기 모든 것이 나의 힘이 아닌 하나님의 힘으로 되어 질 수 있도록 되어지는 전도',
        liveIn: '경기(의정부)',
        imgSrc: '',
    },
    {
        id: 78,
        name: '이예은',
        admission: 10,
        graduated: 11,
        prayerTopic: '그리스도 앞에 무릎 꿇게',
        liveIn: '경기(수원)',
        imgSrc: '',
    },
    {
        id: 79,
        name: '신다영',
        admission: 12,
        graduated: 12,
        prayerTopic: '그리스도 앞에 무릎 꿇게',
        liveIn: '경기(수원)',
        imgSrc: '',
    },
    {
        id: 80,
        name: '김여경',
        admission: 11,
        graduated: 12,
        prayerTopic: '행1:1-8',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 81,
        name: '박대현',
        admission: 10,
        graduated: 10,
        prayerTopic: '',
        liveIn: '경기(수원)',
        imgSrc: '',
    },
    {
        id: 82,
        name: '최희원',
        admission: 13,
        graduated: 12,
        prayerTopic: '1,3,8속에서의 업으로 현장살릴 수 있는 RT되도록',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 83,
        name: '박준하',
        admission: 11,
        graduated: 13,
        prayerTopic: '언제나 성령인도 받을 수 있게',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 84,
        name: '손영한',
        admission: 12,
        graduated: 14,
        prayerTopic: '그리스도로 모든 것 할 수 있다는 증인되게',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 85,
        name: '정에스더',
        admission: 13,
        graduated: 12,
        prayerTopic:
            '행1:1,3,8의 삶 살도록, 하나님이 만드신 나, 나의 것, 나의 현장을 발견하도록, 예수 그리스도 모든 문제 해결자 되심에 증인이 되는 삶을 살도록',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 86,
        name: '윤희주',
        admission: 13,
        graduated: 14,
        prayerTopic: '갈2:20, 창41:38, 헹27:24, 히11:38',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 87,
        name: '정우석',
        admission: 12,
        graduated: 14,
        prayerTopic:
            '237개국 다민족 목회자, 후대 살리는 전도자의 직무 다하는 중직자',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 88,
        name: '최준우',
        admission: 14,
        graduated: 14,
        prayerTopic:
            '그리스도의 제자, 하나님의 영에 감동된 사람,렘넌트지도자, 하나님 자녀',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 89,
        name: '김유림',
        admission: 15,
        graduated: 15,
        prayerTopic:
            '영적 서밋, 날마다 복음의 감사를 회복하고 나의 그리스도를 누리며 말씀의 흐름 속에, 3가지 시스템 속에만 있게',
        liveIn: '경기(안산)',
        imgSrc: '',
    },
    {
        id: 90,
        name: '박준영',
        admission: 15,
        graduated: 17,
        prayerTopic:
            '마4:19 치유선교사, 말씀 따라가는 렘넌트메이커, 가정복음화',
        liveIn: '경기(수원)',
        imgSrc: '',
    },
    {
        id: 91,
        name: '이성화',
        admission: 16,
        graduated: 17,
        prayerTopic:
            '창1:27 하나님의 형상 대로 오직 그리스도로 행복한 사람, 그리스도 안에서 따라오는 19가지 응답 받도록',
        liveIn: '경기(안산)',
        imgSrc: '',
    },
    {
        id: 92,
        name: '김유니아',
        admission: 14,
        graduated: 17,
        prayerTopic:
            '고전16:18 주와 주의 종을 시원케하는 자, 사6:1-13 렘넌트 운동, 237RUTC 메이커, RUTC 3기업의 원조의 응답 받는 자',
        liveIn: '경기(안산)',
        imgSrc: '',
    },
    {
        id: 93,
        name: '양세진',
        admission: 16,
        graduated: '',
        prayerTopic: '오직 그리스도의 증인이 되게',
        liveIn: '경기',
        imgSrc: '',
    },
    {
        id: 94,
        name: '정재훈',
        admission: 3,
        graduated: 5,
        prayerTopic: '오직 그리스도의 증인이 되게',
        liveIn: '인천',
        imgSrc: '',
    },
    {
        id: 95,
        name: '민요한',
        admission: 2,
        graduated: 6,
        prayerTopic: '오직 그리스도의 증인이 되게',
        liveIn: '인천',
        imgSrc: '',
    },
    {
        id: 96,
        name: '최준영',
        admission: 10,
        graduated: 9,
        prayerTopic:
            '언약의 개인화, 말씀의 교회화, 성령충만의 현장화가 되어 전도자의 삶으로 증인되도록',
        liveIn: '인천',
        imgSrc: '',
    },
    {
        id: 97,
        name: '양윤아',
        admission: 11,
        graduated: 12,
        prayerTopic: '예배회복, 흑암문화에 흔들리지 않게, 현장 분위기 정복',
        liveIn: '인천',
        imgSrc: '',
    },
    {
        id: 98,
        name: '이형경',
        admission: 15,
        graduated: 13,
        prayerTopic:
            '나의 땅 끝에서 그리스도만 전할 수 있게, 언제나 하나님계획 질문 하는 것 잊지 않고 방향 맞춰갈 수 있게',
        liveIn: '인천',
        imgSrc: '',
    },
    {
        id: 99,
        name: '하주용',
        admission: 13,
        graduated: 16,
        prayerTopic:
            '7핵 되신 그리스도를 붙잡고 1,3,8,14의 기도 속으로 들어가게, 상명대학 속에서 성경적 전도 운동 일어나게',
        liveIn: '인천',
        imgSrc: '',
    },
    {
        id: 100,
        name: '김중현',
        admission: 11,
        graduated: '',
        prayerTopic: '말씀의 흐름 탈 수 있게',
        liveIn: '인천',
        imgSrc: '',
    },
    {
        id: 101,
        name: '이윤수',
        admission: 11,
        graduated: 10,
        prayerTopic:
            '아무도 막을 수 없는 하나님의 절대 계획 모슬렘 복음화, 매일 그리스도가 보이고, 느껴지고 만져지고, 동행하는 삶, 하나님께 질문하고 하나님의 음성을 듣는 예배자, 하나님 앞에서 성령 인도받으며 갑절의 영감을 구하는 기도하는 자',
        liveIn: '인천',
        imgSrc: '',
    },
    {
        id: 101,
        name: '정아람',
        admission: 1,
        graduated: 3,
        prayerTopic: '',
        liveIn: '충청(천안)',
        imgSrc: '',
    },
    {
        id: 102,
        name: '현재성',
        admission: 3,
        graduated: 3,
        prayerTopic: '',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 103,
        name: '현선미',
        admission: 5,
        graduated: 7,
        prayerTopic:
            '하나님과 방향이 같은 자, 마음이 통하는 자 되길/강단 속에서 3오늘, 5력 회복',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 104,
        name: '이용수',
        admission: 6,
        graduated: 9,
        prayerTopic: '항상 하나님과 동행하는 삶을 살아갈 수 있도록',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 105,
        name: '정태양',
        admission: 9,
        graduated: 9,
        prayerTopic: '모든 것에 오직 그리스도로 결론난 증인',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 106,
        name: '유푸름',
        admission: 9,
        graduated: 9,
        prayerTopic: '행1,3,8로 행복한 전도제자, 3서밋의 주역',
        liveIn: '충청(대전)',
        imgSrc: '',
    },
    {
        id: 107,
        name: '유아름',
        admission: 11,
        graduated: 10,
        prayerTopic: '왕을 상대할 자(고전2:2)',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 108,
        name: '박혜란',
        admission: 7,
        graduated: 9,
        prayerTopic: '',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 109,
        name: '한예원',
        admission: 12,
        graduated: 14,
        prayerTopic: '사42:6~8 백성의 언약, 이방의 빛',
        liveIn: '충청(공주)',
        imgSrc: '',
    },
    {
        id: 110,
        name: '설석재',
        admission: 6,
        graduated: 7,
        prayerTopic: '전도자의 식주인',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 111,
        name: '김관엽',
        admission: 13,
        graduated: 16,
        prayerTopic:
            '행복한 복음 전도자로, 현장 살리는 렘넌트지도자가 되게, 대학과 현장 살리는 치유선교사의 응답 속으로 들어가게',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 112,
        name: '정바울',
        admission: 5,
        graduated: '',
        prayerTopic: '',
        liveIn: '충청(천안)',
        imgSrc: '',
    },
    {
        id: 113,
        name: '정다윗',
        admission: '',
        graduated: '',
        prayerTopic: '',
        liveIn: '충청(대전)',
        imgSrc: '',
    },
    {
        id: 114,
        name: '한요나',
        admission: 12,
        graduated: '',
        prayerTopic: '',
        liveIn: '충청(대전)',
        imgSrc: '',
    },
    {
        id: 115,
        name: '오하은',
        admission: 12,
        graduated: '',
        prayerTopic: '',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 116,
        name: '임채원',
        admission: 16,
        graduated: '',
        prayerTopic: '하나님과 함께 최고로 누리는 후대사역자',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 117,
        name: '최예나',
        admission: 15,
        graduated: 17,
        prayerTopic:
            '오직 복음만 누리고 전하는 전도제자되길, 사66:18-24 사6:8 선교사의 소명을 가지고 삿2:10의 사명을 감당케',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 118,
        name: '김반석',
        admission: 17,
        graduated: 17,
        prayerTopic:
            '24기도가 되어지도록 복음 시스템을 구축하고 삶에서 복음 적용화에 성공하게 하옵소서',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 119,
        name: '한누림',
        admission: 12,
        graduated: 17,
        prayerTopic: '모든 것인 오직의 답을 가진 마가다락방의 선교사(행2:1-47)',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 120,
        name: '오시언',
        admission: 18,
        graduated: '',
        prayerTopic: '렘넌트전도운동의 증인',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 121,
        name: '송지원',
        admission: 18,
        graduated: '',
        prayerTopic: '대학에서 성령인도 받게 하옵소서',
        liveIn: '충청',
        imgSrc: '',
    },
    {
        id: 122,
        name: '김양재',
        admission: 2,
        graduated: 4,
        prayerTopic: '237, 치유, 서밋의 자리에서 렘넌트를 섬기도록',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 123,
        name: '정지혜',
        admission: 4,
        graduated: 4,
        prayerTopic: '',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 124,
        name: '김건',
        admission: 3,
        graduated: 5,
        prayerTopic: '모두가 잘 되었으면',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 125,
        name: '박상현',
        admission: 4,
        graduated: 11,
        prayerTopic: '각인, 뿌리, 체질을 바꾸고 언약적 발판으로 설 수 있도록',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 126,
        name: '남주혜',
        admission: 13,
        graduated: 18,
        prayerTopic:
            '오직 복음으로 행복한 하나님의 자녀(예배자), RLS전도운동의 주역(62가지 삶의 응답-20비젼), 237RUTC(5천종족) 회당운동의 주역(RLS운동본부)',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 128,
        name: '박태웅',
        admission: 7,
        graduated: 7,
        prayerTopic:
            '말씀으로 나의 인생이 완생 될 수 있게 아직은 미생이지만 말씀으로 인도받아 나의 가족과 훗날 미래의 배우자를 기도응답 받고싶다. 솔직히 세상 사는게 힘들고 기도도 잘 안되고 말씀으로 중심이 안 잡히기에 기도로 힘을 주셨으면 한다',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 129,
        name: '정주찬',
        admission: 11,
        graduated: 11,
        prayerTopic: '현장살리는 전도자되게',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 130,
        name: '김무비',
        admission: 13,
        graduated: 13,
        prayerTopic:
            '흔들리지 않는 믿음, 이사야60장, 말 앞에서는 인생, 시대에 필요한 전도자',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 131,
        name: '유한솔',
        admission: 11,
        graduated: 11,
        prayerTopic: '항상 하는 일 마다 하나님의 계획을 찾을 수 있도록',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 132,
        name: '문현준',
        admission: 15,
        graduated: '',
        prayerTopic: '',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 133,
        name: '이현민',
        admission: 13,
        graduated: '',
        prayerTopic:
            '고전10:31 하나님의 영광을 위해 사는 지도자, 그리스도가 나에게 충분, 완전,모든 것 되게',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 134,
        name: '김태희',
        admission: 16,
        graduated: 15,
        prayerTopic: 'Always  성령인도, 성령충만, 오력',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 135,
        name: '김사명',
        admission: 1,
        graduated: 2,
        prayerTopic: '20가지 전략의 시스템',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 136,
        name: '곽한상',
        admission: 7,
        graduated: 7,
        prayerTopic:
            'Remnant 7명의 응답도 좋지만 그들이 응답받기까지의 과정에 집중, 육체의 일을 버리고 성령의 9가지 열매를 통해 오는 응답 성취, 무리를 떠나 제자의 대열에 설 수 있는 한 주, 진정으로 모든 것을 완전히 아시는 주님을 인정하고 나의 모든 것을 내려놓기, 전주지역 목회자분들을 모두 지원할 수 있는 복음적, 선교적 기업 세우게(그리고 이를 위한 청년 Team 만남의 축복)',
        liveIn: '호남(전주)',
        imgSrc: '',
    },
    {
        id: 137,
        name: '채종림',
        admission: 7,
        graduated: '',
        prayerTopic: '전주 현장 살리고 지역살리는 전도자가 되게',
        liveIn: '호남(전주)',
        imgSrc: '',
    },
    {
        id: 138,
        name: '채성림',
        admission: 7,
        graduated: '',
        prayerTopic: '',
        liveIn: '호남(전주)',
        imgSrc: '',
    },
    {
        id: 139,
        name: '최윤영',
        admission: 6,
        graduated: '',
        prayerTopic: '',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 140,
        name: '김태양',
        admission: 13,
        graduated: 12,
        prayerTopic:
            '복음이 아닌 오직 복음을 가진 자, 전도하는 사람이 아닌 오직 전도하는 자, 실력 있는 자가 아닌 Remnant Leader, 내 삶이 영적 서밋의 시스템 속에 있게 하시고 237나라에 영적 서밋의 시스템을 까는 자가 되게 하옵소서',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 141,
        name: '곽현상',
        admission: 9,
        graduated: 9,
        prayerTopic: '하나님이 계획하신 방향따라 현장살리기',
        liveIn: '호남',
        imgSrc: '',
    },
    {
        id: 142,
        name: '이최상',
        admission: 8,
        graduated: 7,
        prayerTopic:
            '하나님이 만드신 나를 찾게, 나의 현장에 맡겨주신 혼들을 품을 수 있게, 오직 예수가 중심이 되고 우선순위가 되어지게',
        liveIn: '대경(왜관)',
        imgSrc: '',
    },
    {
        id: 143,
        name: '심다솔',
        admission: 7,
        graduated: 7,
        prayerTopic:
            '나의 모든 평생을 하나님께 드리는 나 실인(삼상 1:28)의 인생이 되게 하옵소서, 참된 그리스도의 풍성함을 전하는 237장애우 복음화의 전도자(엡3:8)-특수 현장 살릴 장애우 학교(RDS), 사량부 RUTC, 그리스도로 충분 완전 모든 것임을 매 순간 고백하는 전도자',
        liveIn: '대경(사천)',
        imgSrc: '',
    },
    {
        id: 144,
        name: '권현석',
        admission: 11,
        graduated: 10,
        prayerTopic: '현실에 안주하는 것이 아닌 언약의 여정을 걸을 수 있도록',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 145,
        name: '조성수',
        admission: 7,
        graduated: 7,
        prayerTopic:
            '모든 문제, 상황, 위기 속에서 하나님의 하나님의 계획 발견. 각인 뿌리 체질을 치유하고 오직 그리스도로 완전 답이 나고 그리스도가 아니면 아무것도 되어지지 않게',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 147,
        name: '황정연',
        admission: 7,
        graduated: 7,
        prayerTopic:
            '내가 서 있는 현장에 하나님 나라가 임하도록 하옵소서, 예배드릴 수 있는 영적 상태가 회복되도록 하옵소서, 렘넌트지도자의 정체성을 회복하도록 하옵소서',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 148,
        name: '김지현',
        admission: 12,
        graduated: 11,
        prayerTopic: '예배 성공, 기도성공할 수 있는 영적상태 회복',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 149,
        name: '이화평',
        admission: 10,
        graduated: 12,
        prayerTopic: '',
        liveIn: '대경(경주)',
        imgSrc: '',
    },
    {
        id: 150,
        name: '박예나',
        admission: 13,
        graduated: 12,
        prayerTopic:
            '만 가지 있어도 한 가지가 없어망하는 시대에 한 가지, 그리스도 복음의 증인으로서도 록, 나의 매일이 언약의 여정 속에 있음을 확인하고 생명 되신 그리스도를 매일 만나도록',
        liveIn: '대경(경주)',
        imgSrc: '',
    },
    {
        id: 151,
        name: '김보민',
        admission: 14,
        graduated: 13,
        prayerTopic:
            '예수가 그리스도, 유일한 답을 항상 잊지 않게 하시고, 일평생 하나님께 영광 돌리게 하옵소서, 어제보다 오늘 오늘보다 내일 주님을 더 사랑하게 하옵소서',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 152,
        name: '박수빈',
        admission: 15,
        graduated: 13,
        prayerTopic:
            '고후6:9-10 그리스도로 부유한 영적 지도자, 요일 5:14 청소년 현장에 하나님의 것을 담대히 구하는 현장 전도자, 수14:12 가장 안 보이는 자리에서 교회의 빈 곳을 섬기는 갈렙과 같은 중직자',
        liveIn: '대경(왜관)',
        imgSrc: '',
    },
    {
        id: 153,
        name: '서요셉',
        admission: 13,
        graduated: 13,
        prayerTopic:
            '하나님이 나를 시대와 교회를 치유하는 영적 의사로 부르신 정체성 대로 하나님이 주신 복음, 신분, 권세, 보좌의 능력, 세계복음화의 언약을 가지고 현장에서 하나님께 영광 돌리는 RTL 되도록 하옵소서',
        liveIn: '대경(울산)',
        imgSrc: '',
    },
    {
        id: 154,
        name: '이재호',
        admission: 14,
        graduated: 13,
        prayerTopic:
            '237나라의 후대들 살리는 RT 전도운동, 237RUTC 운동에 쓰임 받는 삶 살도록 하옵소서, RT들 앞에 전도의 증인으로 서게 하옵소서, 창3장의 내가 무너지고 오직 그리스도만 남도록 하옵소서',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 155,
        name: '윤한솔',
        admission: 16,
        graduated: 14,
        prayerTopic: '예배드릴 수 있는 영적상태 회복되도록',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 156,
        name: '최준우',
        admission: 14,
        graduated: 14,
        prayerTopic:
            '구원의 길 확립의 시간, 하나님의 절대 계획 앞에 무릎 꿇을 수 있도록',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 157,
        name: '표준',
        admission: 10,
        graduated: 12,
        prayerTopic: '하나님이 원하시는 일에 부르신다면 결단할 수 있도록',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 158,
        name: '정명수',
        admission: 10,
        graduated: 12,
        prayerTopic:
            '전 세계 7천만 농아인 복음화, 농아인 RUTC를 세울 목회자를 돕고 헌신할 중직자',
        liveIn: '대경(경산)',
        imgSrc: '',
    },
    {
        id: 159,
        name: '안예인',
        admission: 12,
        graduated: '',
        prayerTopic: '복음이 필요해지게',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 160,
        name: '오명빈',
        admission: 13,
        graduated: '',
        prayerTopic: '',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 161,
        name: '정효진',
        admission: 15,
        graduated: '',
        prayerTopic: '',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 162,
        name: '손주현',
        admission: 8,
        graduated: '',
        prayerTopic: '',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 163,
        name: '류동희',
        admission: 8,
        graduated: '',
        prayerTopic: '',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 164,
        name: '이윤지',
        admission: 9,
        graduated: '',
        prayerTopic: '',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 165,
        name: '최연호',
        admission: 11,
        graduated: '',
        prayerTopic: '복음이 내게 필요해지도록',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 166,
        name: '김보현',
        admission: 15,
        graduated: '',
        prayerTopic: '',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 167,
        name: '홍인기',
        admission: 15,
        graduated: 15,
        prayerTopic:
            '현장에 가서도 무너지지 않고 정체성 누리게, 공무원 선교사로 부름받을 수 있도록',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 168,
        name: '박형배',
        admission: 17,
        graduated: 15,
        prayerTopic:
            '군 현장 속에서 절대로 내 정체성 잃지 않도록, 지금 있는 이 현장을 불신앙하며 바라보는게 아닌 선교 현장으로 볼 수 있도록, 지금 섬기고 있는 군 교회(쌍호 교회) 전역하는 날까지 온맘 다해 섬길 수 있게, 이곳에서 있는 시간을 통해 영적으로 성숙해 질 수 있도록',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 169,
        name: '정소명',
        admission: 15,
        graduated: 16,
        prayerTopic:
            '문화 현장을 살리는 문화치유선교사 응답 속으로 들어가게, 1,3,8 + 14의 시스템 가지고 24언약의 여정을 가지고 영남대 복음화의 응답 누리게(삼상7:1-15)',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 170,
        name: '김영빈',
        admission: 16,
        graduated: '',
        prayerTopic:
            '어디서든 W.I.O 누리는 하나님의 자녀, 237의 빈 곳을 살리는 차세대 선교사, 날마다 예수 그리스도가 깊어지는 그리스도의 대사, RUTC운동의 바톤을 이을 렘넌트지도자',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 171,
        name: '유영균',
        admission: 14,
        graduated: '',
        prayerTopic: '한 평생 믿음에 대해 누릴 수 있도록',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 172,
        name: '이선웅',
        admission: 18,
        graduated: 21,
        prayerTopic:
            '기도의 사람, 롬16:1-20, 25-27 창12:1-3 고전13:1-13 빌4:6-7 단1:8-9 욥23:10 전7:21',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 173,
        name: '지상현',
        admission: 17,
        graduated: 21,
        prayerTopic:
            '그리스도 누리고 영적 회복과 미션홈 생활을 제대로 할 수 있도록',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 174,
        name: '배다정',
        admission: 16,
        graduated: 21,
        prayerTopic:
            '현장에서 렘넌트 지도자의 정체성 누림, 창 1:3, 사 59:21, 신 6:4-9 가정 복음화를 통한 후대 복음화, 나의 업을 통해 237 복음화, 매일 그리스도를 인격으로 만나기',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 175,
        name: '김승모',
        admission: 11,
        graduated: 10,
        prayerTopic: '영적인 눈으로 먼저 바라볼 수 있는 시간표',
        liveIn: '대경(대구)',
        imgSrc: '',
    },
    {
        id: 176,
        name: '박규로',
        admission: 8,
        graduated: 9,
        prayerTopic: '',
        liveIn: '대경(경주)',
        imgSrc: '',
    },
    {
        id: 177,
        name: '유효진',
        admission: 3,
        graduated: 3,
        prayerTopic: '',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 178,
        name: '전석민',
        admission: 1,
        graduated: 5,
        prayerTopic:
            '하나님자녀, 렘넌트 지도자 정체성, 나의 현주소-빌4:13,롬8:31-39, 행9:15',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 179,
        name: '신효진',
        admission: 2,
        graduated: 3,
        prayerTopic: '',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 180,
        name: '강경원',
        admission: 2,
        graduated: 4,
        prayerTopic: '1,3,8을 가지고 14절의 시간',
        liveIn: '부경(함양)',
        imgSrc: '',
    },
    {
        id: 181,
        name: '허지훈',
        admission: 1,
        graduated: 6,
        prayerTopic: '갑절의 영감, 성령충만',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 182,
        name: '전민형',
        admission: 7,
        graduated: 7,
        prayerTopic:
            '하나님이 만드신 내가 발견되어지는 영적인 힘을 회복하는 아침 저녁 시간이 누려지고 체험되게 하소서',
        liveIn: '부경(부산)',
        imgSrc: '',
    },
    {
        id: 183,
        name: '하성현',
        admission: 5,
        graduated: 7,
        prayerTopic:
            '나의 잘못된 생각, 각인된 것 내 힘으로 말고 살아계시고 나와 항상 함께 하시는 나의 하나님 앞에서 치유하는 역사가 이루어지고 이를 통해 나의 주위, 현장, 가정 가문, 교회, 목회자, 후대가 살아나는 응답 받기를 원합니다',
        liveIn: '부경(부산)',
        imgSrc: '',
    },
    {
        id: 184,
        name: '최재웅',
        admission: 8,
        graduated: 8,
        prayerTopic: '그리스도의 사랑',
        liveIn: '부경(부산)',
        imgSrc: '',
    },
    {
        id: 185,
        name: '정나래',
        admission: 8,
        graduated: 7,
        prayerTopic: '오직의 이유와 증인',
        liveIn: '부경(함양)',
        imgSrc: '',
    },
    {
        id: 186,
        name: '강문규',
        admission: 9,
        graduated: 8,
        prayerTopic: '단6:10',
        liveIn: '부경(부산)',
        imgSrc: '',
    },
    {
        id: 187,
        name: '강정훈',
        admission: 5,
        graduated: 8,
        prayerTopic: '롬1:16-17, 민족, 세계 살릴 성령충만과 오력',
        liveIn: '부경(양산)',
        imgSrc: '',
    },
    {
        id: 188,
        name: '김민혁',
        admission: 10,
        graduated: 10,
        prayerTopic: '20가지 전략을 실제체험하는 전도자',
        liveIn: '부경(부산)',
        imgSrc: '',
    },
    {
        id: 189,
        name: '강하라',
        admission: 12,
        graduated: 12,
        prayerTopic: '',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 189,
        name: '강하라',
        admission: 12,
        graduated: 12,
        prayerTopic: '',
        liveIn: '부경(부산)',
        imgSrc: '',
    },
    {
        id: 190,
        name: '양은진',
        admission: 11,
        graduated: 13,
        prayerTopic:
            '인재은행 설립, 청소년 치유센터 설립 – 복음을 몰라 죽어가는 청소년 살리는 치유센터(학교형 RUTC), 내가 하는 모든 일이 하나님의 이름을 높이는데, 하나님께 영광 돌리는 일이 될 수 있도록(고전 10:31), 나만의 기도실, RT와 후대를 위한 RT 룸, 237개 나라와 선교를 위한 선교 룸',
        liveIn: '부경(부산)',
        imgSrc: '',
    },
    {
        id: 191,
        name: '이현수',
        admission: 7,
        graduated: 7,
        prayerTopic: '237나라 RUTC 완성',
        liveIn: '부경(함양)',
        imgSrc: '',
    },
    {
        id: 193,
        name: '김준수',
        admission: 16,
        graduated: 16,
        prayerTopic:
            '절대 언약, 절대 계획, 절대 응답 속에서 렘넌트지도자의 정체성으로 현장 살리는 대학선교사로 세워지게, 서밋 타임, 서밋 자세, 서밋 그릇을 준비하게',
        liveIn: '부경(부산)',
        imgSrc: '',
    },
    {
        id: 194,
        name: '임호세',
        admission: 1,
        graduated: '',
        prayerTopic: '',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 195,
        name: '유하은',
        admission: 10,
        graduated: '',
        prayerTopic: '',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 196,
        name: '백종빈',
        admission: 11,
        graduated: '',
        prayerTopic: '군선교사의 언약이 성취되는 시간이 되도록',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 197,
        name: '이주은',
        admission: 9,
        graduated: '',
        prayerTopic: '',
        liveIn: '부경(부산)',
        imgSrc: '',
    },
    {
        id: 198,
        name: '임모세',
        admission: 11,
        graduated: '현장을 살릴 수 있는 행1:1,3,8의 증인, 예배 성공',
        prayerTopic: '',
        liveIn: '부경(부산)',
        imgSrc: '',
    },
    {
        id: 199,
        name: '김기환',
        admission: 12,
        graduated: '',
        prayerTopic: '',
        liveIn: '부경(부산)',
        imgSrc: '',
    },
    {
        id: 200,
        name: '정세희',
        admission: 14,
        graduated: '',
        prayerTopic: '',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 201,
        name: '이은혜',
        admission: 9,
        graduated: '',
        prayerTopic: '',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 202,
        name: '이현정',
        admission: 11,
        graduated: 13,
        prayerTopic: '예배 성공, 학업 집중, 현장 정복',
        liveIn: '부경(통영)',
        imgSrc: '',
    },
    {
        id: 203,
        name: '김영길',
        admission: 4,
        graduated: 5,
        prayerTopic: '하나님 은혜 속에서',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 204,
        name: '백준',
        admission: 4,
        graduated: 6,
        prayerTopic:
            '오직의 비밀 속으로 더욱 들어가며 성령 내주, 인도, 역사를 머리가 아닌 가슴으로 체험할 수 있도록',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 205,
        name: '김다미',
        admission: 2,
        graduated: 7,
        prayerTopic: '',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 206,
        name: '이성수',
        admission: 11,
        graduated: 10,
        prayerTopic: '오직 예수 그리스도의 증인, 20가지 전략 체험',
        liveIn: '부경(통영)',
        imgSrc: '',
    },
    {
        id: 207,
        name: '백준혁',
        admission: 5,
        graduated: '',
        prayerTopic: '',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 208,
        name: '임성언',
        admission: 16,
        graduated: '',
        prayerTopic: '',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 209,
        name: '정주헌',
        admission: 9,
        graduated: 9,
        prayerTopic: '하나님의 손길 인식하기',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 210,
        name: '전민경',
        admission: 4,
        graduated: 7,
        prayerTopic: '전도자의 삶 62가지 삶의 증인, 사25:6-8',
        liveIn: '부경(함양)',
        imgSrc: '',
    },
    {
        id: 211,
        name: '최용혁',
        admission: 1,
        graduated: 2,
        prayerTopic:
            '왕하2:1-15, 신21:5, 21세기 도단성 지도자, 성삼위 하나님 배경과 권세',
        liveIn: '부경(함양)',
        imgSrc: '',
    },
    {
        id: 212,
        name: '강현정',
        admission: 4,
        graduated: 6,
        prayerTopic: '20가지 전략의 증인',
        liveIn: '부경(함양)',
        imgSrc: '',
    },
    {
        id: 213,
        name: '서성영',
        admission: 14,
        graduated: 17,
        prayerTopic:
            '전 세계를 살리는 0.1%중직자, 시대를 살리는 미션홈 운동의 주역, RT 없는 오늘을 살아가지 않도록',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 214,
        name: '서채영',
        admission: 14,
        graduated: 17,
        prayerTopic:
            '신6:4-9. 사60장의 RM, With, immanuel, Oneness, 그리스도로 매일 감사 감격',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 215,
        name: '양지훈',
        admission: 13,
        graduated: 17,
        prayerTopic:
            '시103:19-22 보좌의 증인, 현장을 알고 현장을 살리는 지도자',
        liveIn: '부경',
        imgSrc: '',
    },
    {
        id: 216,
        name: '장주은',
        admission: 13,
        graduated: 17,
        prayerTopic:
            '요21:15-18, 시71:18, 7핵 되신 그리스도, 날이 가면 갈수록 그리스도를 더욱더 사랑하고 그 사랑으로 깊어지고 넓어지고 높아지도록, 하나님의 최고 관심이자 사랑인 렘넌트(후대) 현장에서 눈을 뜨고 눈을 감도록, 행1:1,3,8,14, 2:1-28:31 성경적 20전도운동의 증인, 행17:,18:4, 19:21, 23:11, 27:24 회당 운동, 로마 운동, RUTC 운동',
        liveIn: '부경',
        imgSrc: '',
    },
];
